/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.restadoapp.androidappsettings;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import android.net.Uri;
import android.content.Intent;
import android.provider.Settings;

import android.app.Activity;


@Kroll.module(name="Androidappsettings", id="com.restadoapp.androidappsettings")
public class AndroidappsettingsModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "AndroidappsettingsModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public AndroidappsettingsModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public String example()
	{
		Log.d(LCAT, "example called");
		return "hello world";
	}

	// Properties
	@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(LCAT, "get example property");
		return "hello world";
	}


	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(LCAT, "set example property: " + value);
	}

	@Kroll.method
	public void go_to_app_settings () {//final Activity context) {
	    
		Activity context = TiApplication.getInstance().getCurrentActivity(); //actually an activity, not a context?
		//TiApplication context = TiApplication.getInstance();
		
	    final Intent i = new Intent();
	    i.setAction(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
	    i.addCategory(Intent.CATEGORY_DEFAULT);
	    i.setData(Uri.parse("package:" + context.getPackageName()));
	    i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
	    i.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
	    i.addFlags(Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS);
	    context.startActivity(i);
	}
}

